### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by ilyaluk-old**
Added seek, playing position in titlebar for gstreamer and slightly improved thread matching regex

### CODE REVIEW

**Comment by ValdikSS** [comment]
You can't seek a video because the saved file would be broken. It is saved right as it played using gstreamer itself.

**Comment by ilyaluk-old** [comment]
Ouch. At least, current position should work properly. By the way, is there any solution, e.g. downloading in a separate thread?

**Comment by ValdikSS** [comment]
Well yes, but that would require some modifications. I could think of 3 different approaches for this issue:
1. Download file into memory or on a storage device and play it simultaneously. Not sure if this won't introduce other problems.
2. "Seek" only forward just by speeding up the video.
3. Just download file and play it separately. Would consume double bandwidth and traffic. Stupid.

Can we drop a seek support for now? Could you make another pull request without seeking modifications?

**Comment by ilyaluk-old** [comment]
Yep, of course.

**Pull request closed without merging**
